name: blue_bit
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/h1.jpg
    - assets/icons/chat.svg
    - assets/icons/facebook.svg
    - assets/icons/google-plus.svg
    - assets/icons/login.svg
    - assets/images/login_bottom.png
    - assets/images/main_bottom.png
    - assets/images/main_top.png
    - assets/icons/signup.svg
    - assets/images/signup_top.png
    - assets/icons/twitter.svg
    - assets/images/start.png